<MCQCheckBox@CheckBox>:
    color: 0, 0, 0, 1
    size_hint: 0.15, 1


<MCQLabel@ButtonBehavior+Label>:
    text_size: self.size
    valign: 'center'
    font_size: '13sp'
    color: 0, 0, 0, 1


<MCQLabelCheckBox@BoxLayout>:
    text: ''
    group: ''

    MCQCheckBox:
        id: cb
        group: root.group

    MCQLabel:
        on_press: cb._do_press()
        text: root.text


<MCQsGUI>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

    MCQLabelCheckBox:
        text:"option 1"
        group: 'opts'

    MCQLabelCheckBox:
        text:"option 2"
        group: 'opts'

    MCQLabelCheckBox:
        text:"option 3"
        group: 'opts'

    MCQLabelCheckBox:
        text:"option 4"
        group: 'opts'