title: BN Modeller
description: Application for feature dependency modeling and evaluation.
show_downloads: false
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
site:
  url: https://digiratory.github.io/bayes_model/
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
