title: BN Modeller
description: Application for feature dependency modeling and evaluation.
show_downloads: false
google_analytics:
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
